// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250106114135_testData")]
    partial class testData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Açıklama",
                            ImageUrl = "1.jpg",
                            IsActive = true,
                            Price = 10000m,
                            ProductName = "Iphone15",
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Description = "Açıklama",
                            ImageUrl = "2.jpg",
                            IsActive = true,
                            Price = 15000m,
                            ProductName = "Iphone16",
                            Stock = 10
                        },
                        new
                        {
                            Id = 3,
                            Description = "Açıklama",
                            ImageUrl = "3.jpg",
                            IsActive = true,
                            Price = 20000m,
                            ProductName = "Iphone16 Pro",
                            Stock = 10
                        },
                        new
                        {
                            Id = 4,
                            Description = "Açıklama",
                            ImageUrl = "4.jpg",
                            IsActive = true,
                            Price = 25000m,
                            ProductName = "Iphone16 Pro Max",
                            Stock = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
